### ISSUE TITLE
请问该如何配置ipv6子网

### ISSUE THREAD

**Issue by dengchangdong** [gngpp/ninja#247]
项目`docker-compose.yml`配置如下：
```
  ninja:
    container_name: Ninja
    image: gngpp/ninja:latest
    restart: unless-stopped
    privileged: true
    command: run
    ports:
      - 8060:7999
    environment:
      - TZ=Asia/Shanghai
      - DISABLE_WEBUI=true
      - IPV6_SUBNET=2001:470:xxx::/48
    volumes:
      - ./config/chat.openai.com.har:/root/.chat3.openai.com.har 
 ```
ipv6子网是直接路由过来（He.net Tunnelbroker）。

运行报错信息如下：
```
[openai/src/serve/mod.rs:668:13] Check IP request error: error sending request for url (https://ifconfig.me/): error trying to connect: tcp connect error: Network unreachable 
```

请问大佬，该如何配置ipv6子网，谢谢
