### ISSUE TITLE
上传 登录auth  HAR 失败

### ISSUE THREAD

**Issue by Dooy** [gngpp/ninja#464]
我把登录chat.openai.com 的HAR 传到 auth失败
但是我把发送消息的gpt-4的HAR  传到 auth确能成功
他们两的 :pk 不一样吧 一个是 `35536E1E-65B4-4D96-9D97-6ADB7EFF8147`
一个是 `0A1D34FC-659D-4E23-B17B-694DCFCF6A6C`

希望 大佬指导
<img width="1670" alt="image" src="https://github.com/gngpp/ninja/assets/3765401/ce514ba2-f389-43bd-a6d9-7dd5898e08de">
<img width="272" alt="image" src="https://github.com/gngpp/ninja/assets/3765401/570fdb0e-dd48-48f8-9411-3fc057e15e4d">

<img width="491" alt="image" src="https://github.com/gngpp/ninja/assets/3765401/e75ccc97-0672-4f27-a2f1-1d42a1f08d6a">

**Comment by gngpp** [comment]
文件里搜搜有没有相关请求记录就知道了

**Comment by Dooy** [comment]
都有啊 是不是只要把 这个bda 搞出来就好？

<img width="357" alt="image" src="https://github.com/gngpp/ninja/assets/3765401/a923eadb-fb91-42a0-a215-dc63c2dee3e3">

**Comment by gngpp** [comment]
你看看日志，
<img width="1076" alt="image" src="https://github.com/gngpp/ninja/assets/51810656/f339e000-fcb8-44c5-b5e5-90bb7e375327">

或者文件发我邮箱gngppz@gmail.com

**Comment by Dooy** [comment]
2024-01-27T04:45:53.377208Z  WARN request{method=POST uri=/har/upload version=HTTP/1.1}: openai::serve::router::har: [crates/openai/src/serve/router/har/mod.rs:157:13] upload har file check error: control character (\u0000-\u001F) found while parsing a string at line 40 column 29

**Comment by Dooy** [comment]
是不是 文件太大了

**Comment by gngpp** [comment]
不是，看起来是解析json出问题。

**Comment by Dooy** [comment]
文件发过来了

**Comment by gngpp** [comment]
换个浏览器重新抓一份，你不需要真的登录，先输入错误账户和密码提交登录请求完直接提取就行了

**Comment by Dooy** [comment]
收到  谢谢 我再试下
真登录有10M

**Comment by gngpp** [comment]
如果你是浏览器前端应用登录/对话 完全可以不用上传什么har，只需要对接自带的arkose端点就行了，如何接入，看自带的Web UI 登录页，arkose js会hook表单提交获取arkose token才会继续

**Comment by gngpp** [comment]
我这边上传没有问题，这就有点奇怪了，你是什么操作系统，猜测是windows？
<img width="1073" alt="image" src="https://github.com/gngpp/ninja/assets/51810656/ef7f5f7f-9915-4995-b41b-b429e2808af6">

**Comment by Dooy** [comment]
我是 Ubuntu 20.04 LTS (GNU/Linux 5.4.0-28-generic x86_64) ，不过配置不高 1c1g

> 我这边上传没有问题，这就有点奇怪了，你是什么操作系统，猜测是windows？ <img alt="image" width="1073" src="https://private-user-images.githubusercontent.com/51810656/300173230-ef7f5f7f-9915-4995-b41b-b429e2808af6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzNTMxNTMsIm5iZiI6MTcwNjM1Mjg1MywicGF0aCI6Ii81MTgxMDY1Ni8zMDAxNzMyMzAtZWY3ZjVmN2YtOTkxNS00OTk1LWI0MWItYjQyOWUyODA4YWY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI3VDEwNTQxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4ZWFkNjdjMjY0YTE4ODE2Y2UwZGY2MTMzMmYzMGMyZDM1OWIyMTI1M2QzZmE0Y2U2OWMyMGExMzFmNGMyNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VzyC0Znv8DUocA_VgCemVLWZttnhhdPeJiisTp6JQwY">

**Comment by Dooy** [comment]
我前段webui 登录也有问题出现 `Accidentally jumped back to the login homepage, please try again` 提示
然后我翻 issue 是没配置 har, 我想用接口 索性就配置了

应该是内存不够 文件太大导致

> 如果你是浏览器前端应用登录/对话 完全可以不用上传什么har，只需要对接自带的arkose端点就行了，如何接入，看自带的Web UI 登录页，arkose js会hook表单提交获取arkose token才会继续

**Comment by gngpp** [comment]
跳回首页就要确认IP能不能在官网登录了，网页登陆不走内置har，har这东西就是提取个bda，不会占用太大内存

**Comment by Dooy** [comment]
奇怪了 错误账号密码 只有1m 的har
也过不去 还是提示这个错误

<img width="696" alt="image" src="https://github.com/gngpp/ninja/assets/3765401/f76c2c06-2110-4846-91d6-29811ca0e934">

**Comment by Dooy** [comment]
har是JSON文件 我用JSON工具打开时没问题的 也能找到bda

**Comment by Dooy** [comment]
我 docker-compose 应该没问题吧？
先把har 配置上 再解决ip问题
接口 我用 accessToken 搞gpt-4是没问题的
gpt-4的har 上传也没问题

```yml
version: '3'

services:
  ninja:
    image: ghcr.io/gngpp/ninja:latest
    container_name: ninja
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    command: run -L debug --arkose-solver=yescaptcha --arkose-solver-key=xxxx
    ports:
      - "7999:7999"
    volumes:
      - "./har/gpt3:/root/.ninja/gpt3"
      - "./har/gpt4:/root/.ninja/gpt4"
      - "./har/auth:/root/.ninja/auth"
```
