### ISSUE TITLE
CloudFlare Warp is not supported in your region (China), please delete it, or if your VPS IP can be directly connected to OpenAI, you can also delete it

### ISSUE THREAD

**Issue by huaqiesf** [gngpp/ninja#476]
我比较菜，我想问问这里的删除 cloudflare warp是指删除docker-compose 部署步骤里的
 `  warp:
    container_name: warp
    image: ghcr.io/gngpp/warp:latest
    restart: unless-stopped
`
这一段吗，我试着删除它以及上面的depends on warp后，ninja无法启动

**Comment by gngpp** [comment]
抛开warp 国内不支持你也用不了openai啊，还有下一步你可能还要问在docker中怎么用代理

**Comment by huaqiesf** [comment]
> 抛开warp 国内不支持你也用不了openai啊，还有下一步你可能还要问在docker中怎么用代理

我不是这个意思，是因为最开始我在doc界面点击中文查看指南的时候，cloudflare是单独被框起来的，我以为他是一个单独的模块，中文翻译让我会错意了，以为在国内，或者国外vps就不需要这个东西。好吧，现在我了解了

**Comment by gngpp** [comment]
我是不推荐使用docker，相当麻烦
```
version: '3'

services:
  ninja:
    image: gngpp/ninja:latest
    container_name: ninja
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    command: run
    ports:
      - "8080:7999"
```
